# Generated by Django 5.1.4 on 2026-04-29 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom complet')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('poste', models.CharField(max_length=100, verbose_name='Poste')),
                ('salaire', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salaire (FCFA)')),
            ],
            options={
                'verbose_name': 'Employé',
                'verbose_name_plural': 'Employés',
                'ordering': ['nom'],
            },
        ),
    ]
